(function () {
  const units = [
    {
      id: "dreadnought",
      name: "Aegis-01",
      className: "Vanguard",
      subclass: "Dreadnought",
      role: "Durable attacker",
      color: "#e86b5b",
      maxHp: 1680,
      atk: 176,
      def: 132,
      speed: 96,
      accuracy: 0.05,
      evasion: 0,
      maxSp: 100,
      maxEnergy: 110,
      skill: { name: "Overdrive", description: "Heavy single-target damage; lose 8% current HP.", type: "damage", multiplier: 2.2, spCost: 25, selfHpCost: 0.08 },
      ultimate: { name: "Redline Impact", description: "Heavy damage to one enemy lane.", type: "laneDamage", multiplier: 1.85 },
    },
    {
      id: "hunter",
      name: "Needle-02",
      className: "Striker",
      subclass: "Hunter",
      role: "Single-target attacker",
      color: "#f3a84b",
      maxHp: 1160,
      atk: 214,
      def: 92,
      speed: 112,
      accuracy: 0.1,
      evasion: 0.05,
      maxSp: 100,
      maxEnergy: 100,
      skill: { name: "Marked Shot", description: "High single-target damage; stronger against debuffed targets.", type: "damage", multiplier: 2.5, spCost: 25, debuffBonus: 0.3 },
      ultimate: { name: "Terminal Vector", description: "Massive single-target damage.", type: "damage", multiplier: 4.2 },
    },
    {
      id: "blaster",
      name: "Mortar-03",
      className: "Sweeper",
      subclass: "Blaster",
      role: "Lane-wide attacker",
      color: "#e1cf55",
      maxHp: 1260,
      atk: 188,
      def: 102,
      speed: 101,
      accuracy: 0.03,
      evasion: 0,
      maxSp: 100,
      maxEnergy: 120,
      skill: { name: "Lane Saturation", description: "Damage every enemy in the selected lane.", type: "laneDamage", multiplier: 1.45, spCost: 25 },
      ultimate: { name: "Total Coverage", description: "Heavy damage to every enemy.", type: "allDamage", multiplier: 2.25 },
    },
    {
      id: "supporter",
      name: "Relay-04",
      className: "Amplifier",
      subclass: "Supporter",
      role: "Offensive support",
      color: "#73d08a",
      maxHp: 1340,
      atk: 142,
      def: 108,
      speed: 109,
      accuracy: 0,
      evasion: 0.03,
      maxSp: 100,
      maxEnergy: 110,
      skill: { name: "Power Routing", description: "Grant the selected ally ATK Up for two turns.", type: "buff", multiplier: 0.25, duration: 2, spCost: 25 },
      ultimate: { name: "Synchronized Clock", description: "Grant every deployed ally ATK Up and advance them by 20%.", type: "teamAdvance", multiplier: 0.25 },
    },
    {
      id: "hexer",
      name: "Null-05",
      className: "Suppressor",
      subclass: "Hexer",
      role: "Debuff specialist",
      color: "#6fc5cf",
      maxHp: 1280,
      atk: 156,
      def: 104,
      speed: 106,
      accuracy: 0.08,
      evasion: 0,
      maxSp: 100,
      maxEnergy: 100,
      skill: { name: "Cross-Examination", description: "Deal damage and inflict Vulnerable for two turns.", type: "debuffDamage", multiplier: 1.35, duration: 2, spCost: 25 },
      ultimate: { name: "Final Verdict", description: "Damage and Weaken every enemy.", type: "allDebuffDamage", multiplier: 1.55, duration: 2 },
    },
    {
      id: "protector",
      name: "Rampart-06",
      className: "Defender",
      subclass: "Protector",
      role: "Team shielding",
      color: "#7f9ff1",
      maxHp: 1580,
      atk: 126,
      def: 176,
      speed: 94,
      accuracy: 0,
      evasion: 0,
      maxSp: 100,
      maxEnergy: 120,
      skill: { name: "Safe Formation", description: "Shield every deployed ally for 18% of this unit's max HP.", type: "teamShield", multiplier: 0.18, spCost: 25 },
      ultimate: { name: "Absolute Perimeter", description: "Apply a larger shield and cleanse Crowd Control.", type: "teamShieldCleanse", multiplier: 0.32 },
    },
    {
      id: "medic",
      name: "Patch-07",
      className: "Healer",
      subclass: "Medic",
      role: "Restorative support",
      color: "#c48be8",
      maxHp: 1420,
      atk: 132,
      def: 112,
      speed: 104,
      accuracy: 0,
      evasion: 0.02,
      maxSp: 100,
      maxEnergy: 100,
      skill: { name: "Rapid Treatment", description: "Restore one ally's HP.", type: "heal", multiplier: 1.65, spCost: 25 },
      ultimate: { name: "Mass Recovery", description: "Restore HP to every deployed ally.", type: "teamHeal", multiplier: 1.35 },
    },
  ];

  const enemies = [
    { id: "guard-a", name: "Guard Block", color: "#dc6176", lane: "front", column: 2, maxHp: 1500, atk: 158, def: 118, speed: 93, accuracy: 0.02, evasion: 0, attackType: "single" },
    { id: "guard-b", name: "Guard Block", color: "#dc6176", lane: "front", column: 4, maxHp: 1500, atk: 158, def: 118, speed: 97, accuracy: 0.02, evasion: 0, attackType: "single" },
    { id: "caster", name: "Rear Caster", color: "#9d72d8", lane: "rear", column: 2, maxHp: 1180, atk: 176, def: 88, speed: 105, accuracy: 0.08, evasion: 0.04, attackType: "lane" },
    { id: "drone", name: "Rear Drone", color: "#6f92bd", lane: "rear", column: 4, maxHp: 920, atk: 145, def: 80, speed: 116, accuracy: 0.04, evasion: 0.1, attackType: "single" },
  ];

  window.SGBU = window.SGBU || {};
  window.SGBU.data = {
    config: {
      baseAp: 2,
      normalSpGain: 20,
      chargedSpCost: 20,
      ultimateSpGain: 20,
      normalEnergyGain: 20,
      chargedEnergyGain: 20,
      plungeEnergyGain: 20,
      skillEnergyGain: 30,
      level: 80,
      parryWindowScale: 0.72,
    },
    units,
    enemies,
  };
})();
